
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (1, 'Freedman', 'Inchbald', 6, 'in consequat ut nulla sed accumsan felis ut at dolor quis', '113735.91', 'finchbald0@photobucket.com', '697-169-9341');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (2, 'Yardley', 'Lowten', 1, 'ac nibh fusce lacus purus aliquet at feugiat non pretium', '92129.78', 'ylowten1@si.edu', '715-486-5309');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (3, 'Vally', 'Steutly', 10, 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa', '113185.30', 'vsteutly2@shutterfly.com', '847-955-3601');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (4, 'Giulia', 'Muskett', 6, 'ligula nec sem duis aliquam convallis nunc proin at', '96336.20', 'gmuskett3@cornell.edu', '785-319-4496');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (5, 'Gorden', 'Rushby', 8, 'vel lectus in quam fringilla rhoncus mauris', '85628.15', 'grushby4@vkontakte.ru', '488-442-9765');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (6, 'Bethanne', 'Wilflinger', 2, 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem', '106480.79', 'bwilflinger5@ebay.com', '448-258-7715');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (7, 'Lloyd', 'DiDello', 4, 'convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar', '91838.83', 'ldidello6@example.com', '695-358-1706');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (8, 'Giuseppe', 'Kittless', 4, 'convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas', '81215.88', 'gkittless7@people.com.cn', '664-920-9751');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (9, 'Cobby', 'Minshall', 19, 'quis odio consequat varius integer ac leo pellentesque ultrices mattis', '119705.44', 'cminshall8@unesco.org', '994-293-9339');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (10, 'Conn', 'Beagan', 11, 'eu magna vulputate luctus cum sociis natoque penatibus et magnis', '112397.82', 'cbeagan9@oracle.com', '566-409-1565');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (11, 'Wayland', 'Veschi', 8, 'nulla suscipit ligula in lacus curabitur at ipsum', '90578.77', 'wveschia@eventbrite.com', '784-765-7249');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (12, 'Ginny', 'Gribben', 4, 'rutrum nulla nunc purus phasellus', '96759.47', 'ggribbenb@free.fr', '512-332-1040');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (13, 'Spike', 'Winchcum', 18, 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum', '76558.58', 'swinchcumc@google.es', '392-521-1325');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (14, 'Hayward', 'Millimoe', 11, 'at nulla suspendisse potenti cras in purus', '72593.33', 'hmillimoed@goo.ne.jp', '606-853-8423');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (15, 'Foster', 'Featherby', 6, 'elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla', '103158.20', 'ffeatherbye@godaddy.com', '700-906-0086');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (16, 'Eldin', 'Dowtry', 7, 'velit id pretium iaculis diam erat fermentum', '98213.41', 'edowtryf@webeden.co.uk', '769-387-1401');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (17, 'Shelbi', 'Santon', 18, 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id', '113286.42', 'ssantong@nbcnews.com', '386-375-0633');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (18, 'Hi', 'Mordue', 13, 'vestibulum proin eu mi nulla ac enim in tempor', '86343.24', 'hmordueh@slideshare.net', '173-140-7024');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (19, 'Dyan', 'Budgen', 12, 'cum sociis natoque penatibus et magnis', '81985.73', 'dbudgeni@theglobeandmail.com', '170-143-4418');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (20, 'Pietrek', 'Dobrovolski', 9, 'pharetra magna vestibulum aliquet ultrices erat', '72698.99', 'pdobrovolskij@miitbeian.gov.cn', '112-818-3903');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (21, 'Glenn', 'Dodding', 10, 'ac neque duis bibendum morbi non quam', '88415.50', 'gdoddingk@shutterfly.com', '779-824-2848');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (22, 'Libbie', 'Monument', 2, 'in magna bibendum imperdiet nullam orci pede venenatis non sodales sed', '89259.73', 'lmonumentl@ebay.co.uk', '828-995-0195');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (23, 'Keefer', 'Sargeaunt', 3, 'leo odio porttitor id consequat in consequat ut nulla sed accumsan', '112564.98', 'ksargeauntm@pinterest.com', '152-926-0685');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (24, 'Rudie', 'Badger', 11, 'duis consequat dui nec nisi volutpat eleifend donec ut', '90166.97', 'rbadgern@weather.com', '930-492-2552');
insert into employee (id, first_name, last_name, years_experience, languages_known, salary_desired, employee_email, employee_phone) values (25, 'Sawyere', 'Iskow', 19, 'posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut', '109451.53', 'siskowo@xinhuanet.com', '276-668-8100');

